version: "3"

services:
  election-tracker:
    build: .
    volumes:
      - ./backend/history/:/usr/src/app/backend/history/
    ports:
      - 3000:3000
    environment:
      # get these values from the webstie
      MECENAT_ID:
      SESSION_ID:
